dist: xenial
language: python
services:
  - mongodb
  - xvfb
sudo: true

env:
  global:
    - MPLBACKEND: Qt5Agg

addons:
  apt:
    packages:
      - qtbase5-dev

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.7
      env: _CONDA_CHANNEL=lightsource2-tag BS_PROFILE=collection BS_ENV_VERSION=2019C3.0.1
    - os: linux
      python: 3.7
      env: _CONDA_CHANNEL=nsls2forge BS_PROFILE=collection BS_ENV_VERSION=2019C3.0.1

before_install:
  # Get and install miniconda first:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - sh ./miniconda.sh -b -p ~/mc
  - source ~/mc/etc/profile.d/conda.sh  # this makes all conda vars available
  - conda update conda --yes
  - pwd
  - ls -laF
  # Create an IPython profile dir:
  # - mkdir -p ~/.ipython/profile_${BS_PROFILE}
  # - cp -rv $PWD ~/.ipython/
  # - ls -laF ~/.ipython/
  # - ls -laF ~/.ipython/profile_${BS_PROFILE}
  # pyOlog config:
  - cp -v pyOlog-test.conf ~/pyOlog.conf
  - cat ~/pyOlog.conf
  # Databroker config:
  - mkdir ~/.config/databroker/
  - cp smi-test.yml ~/.config/databroker/smi.yml
  # This is not needed anymore as the file is located in the profile dir,
  # and the path is identified automatically by IPython. Keeping it for now
  # in case there are objections from BL staff.
  # # Copy files hardcoded in the startup files:
  # - sudo mkdir -p /home/xf12id/smi/config/
  # - sudo cp -v smi_config-test.csv /home/xf12id/smi/config/smi_config.csv

install:
  - env | sort -u
  - conda create -y -n ${BS_PROFILE}-${BS_ENV_VERSION} -c ${_CONDA_CHANNEL} ${BS_PROFILE}=${BS_ENV_VERSION} python=${PYTHON}
  - conda activate ${BS_PROFILE}-${BS_ENV_VERSION}
  - conda list
  - conda info
  - conda env list
  - echo -e "\n" | caproto-spoof-beamline &

script:
  - |
    command='
    import glob
    ip = get_ipython()
    for f in sorted(glob.glob("startup/*.py")):
        ip.parent._exec_file(f)'
  - OPHYD_CONTROL_LAYER=pyepics EPICS_CA_AUTO_ADDR_LIST=no EPICS_CA_ADDR_LIST=127.0.0.1 ipython -c "$command"
  - OPHYD_CONTROL_LAYER=caproto ipython -c "$command"
