dist: xenial
language: python
services: mongodb
sudo: false

addons:
  apt:
    packages:
      - qtbase5-dev

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.7
      env: BS_PROFILE=collection BS_ENV_VERSION=2019C3.0.1 MPLBACKEND=Qt5Agg

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - sh ./miniconda.sh -b -p ~/mc
  - source ~/mc/etc/profile.d/conda.sh
  - conda update conda --yes
  - pwd
  - ls -laF
  - mkdir -p ~/.ipython/profile_${BS_PROFILE}
  - cp -rv $PWD ~/.ipython/
  - ls -laF ~/.ipython/profile_${BS_PROFILE}
  - echo -e "[DEFAULT]\nurl = http://example.com\nlogbooks = test\nusername = travis\npassword = travis" > ~/pyOlog.conf
  - cat ~/pyOlog.conf
  - mkdir ~/.config/databroker/
  - cp smi-test.yml ~/.config/databroker/smi.yml

install:
  - env | sort -u
  - conda create -y -n ${BS_PROFILE}-${BS_ENV_VERSION} -c nsls2forge ${BS_PROFILE}=${BS_ENV_VERSION} python=${PYTHON}
  - conda activate ${BS_PROFILE}-${BS_ENV_VERSION}
  - conda list
  - conda info
  - conda env list

script:
  - ipython --profile=${BS_PROFILE} -c "print('test')"
