dist: xenial
language: python
services:
  - mongodb
  - xvfb
sudo: true

addons:
  apt:
    packages:
      - qtbase5-dev

env:
  global:
    - MPLBACKEND: Qt5Agg
    - BS_PROFILE: collection
    - BS_ENV_VERSION: 2019C3.0.1
  matrix:
    - _CONDA_CHANNEL=lightsource2-tag OPHYD_CONTROL_LAYER=pyepics
    - _CONDA_CHANNEL=nsls2forge OPHYD_CONTROL_LAYER=pyepics
    - _CONDA_CHANNEL=lightsource2-tag OPHYD_CONTROL_LAYER=caproto
    - _CONDA_CHANNEL=nsls2forge OPHYD_CONTROL_LAYER=caproto

os:
  - linux
python:
  - 3.6
  - 3.7

matrix:
  fast_finish: true

before_install:
  # Get and install miniconda first:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - sh ./miniconda.sh -b -p ~/mc
  - source ~/mc/etc/profile.d/conda.sh  # this makes all conda vars available
  - conda update conda --yes
  - pwd
  - ls -laF
  # Create an IPython profile dir:
  # - mkdir -p ~/.ipython/profile_${BS_PROFILE}
  # - cp -rv $PWD ~/.ipython/
  # - ls -laF ~/.ipython/
  # - ls -laF ~/.ipython/profile_${BS_PROFILE}
  # pyOlog config:
  - cp -v pyOlog-test.conf ~/pyOlog.conf
  - cat ~/pyOlog.conf
  # Databroker config:
  - mkdir ~/.config/databroker/
  - cp smi-test.yml ~/.config/databroker/smi.yml
  # This is not needed anymore as the file is located in the profile dir,
  # and the path is identified automatically by IPython. Keeping it for now
  # in case there are objections from BL staff.
  # # Copy files hardcoded in the startup files:
  # - sudo mkdir -p /home/xf12id/smi/config/
  # - sudo cp -v smi_config.csv /home/xf12id/smi/config/smi_config.csv

  # We will be running a default profile without copying the startup/*.py files
  # into it; the startup files will be executed by explicit commands. But to
  # satisfy the automatic resolution of the "smi_config.csv" file, we will have
  # to copy it into the "default" profile dir.
  - mkdir -p ~/.ipython/profile_default
  - cp -v smi_config.csv ~/.ipython/profile_default/smi_config.csv

install:
  - env | sort -u
  - conda create -y -n ${BS_PROFILE}-${BS_ENV_VERSION} -c ${_CONDA_CHANNEL} ${BS_PROFILE}=${BS_ENV_VERSION} python=${TRAVIS_PYTHON_VERSION}
  - conda activate ${BS_PROFILE}-${BS_ENV_VERSION}
  - conda list
  - conda info
  - conda env list
  - echo -e "\n" | caproto-spoof-beamline &
  # Same reason as in https://github.com/bluesky/tutorial/blob/master/binder/postBuild#L14-L15:
  - ln -sv caproto-repeater ${CONDA_PREFIX}/bin/caRepeater

script:
  - |
    command='
    import glob
    ip = get_ipython()
    for f in sorted(glob.glob("startup/*.py")):
        ip.parent._exec_file(f)'
  - EPICS_CA_AUTO_ADDR_LIST=NO EPICS_CA_ADDR_LIST=127.0.0.1 ipython -c "$command"
